Navbar
Aaron-Goldman/internship-job-portal pull request #6
Opened 2021-03-13 16:30 UTC by Aaron-Goldman

Added navigation bar that displays a site title and a Sign Out button when logged in.

Should be merged after #3.

close #4

2021-03-16 11:05 UTC, ahmed-gz requested changes
Looks ok overall, I would recommend you always open the PR against the branch it's depending on, for example if this PR should only get merged once  [#3](https://github.com/Aaron-Goldman/internship-job-portal/pull/3) is merged, then you should create your branch based of `auth` and open the PR against it, then once the other PR is merged you can simply change the target to master. Otherwise the PR will show changes from the other PR and it will be hard to review.

2021-03-16 11:05 UTC, ahmed-gz commented on src/NavBar.js
> +        </div>
Unless I'm missing something, you don't need extra divs here, you can simply render the button only when logged in:
```
const isLoggedIn = !!auth.user;
//...
<Typography variant="h6" color="inherit" style={{ flexGrow: 1 }}>
  Job Portal
</Typography>
{isLoggedIn && <Button onClick={handleSignOut}>Sign Out</Button>}
```

2021-03-16 15:56 UTC, Aaron-Goldman commented
> Looks ok overall, I would recommend you always open the PR against the branch it's depending on, for example if this PR should only get merged once [#3](https://github.com/Aaron-Goldman/internship-job-portal/pull/3) is merged, then you should create your branch based of `auth` and open the PR against it, then once the other PR is merged you can simply change the target to master. Otherwise the PR will show changes from the other PR and it will be hard to review.

Should I do a `git rebase` now or will that just make things worse since I already opened this PR?

2021-03-17 11:51 UTC, ahmed-gz commented
@Aaron-Goldman I think you will get merge conflicts no matter what you do once the other PR is merged to master, because you included change here that will be merged to master soon, so I would recommend either rebasing this PR and all others to `auth`  or simply start over if it's easier for you by creating new branches based on the previous branch that it's depending on, for example:

- Create `navbar` based on `auth`.
- Create `job-feed` based on `navbar`.
- Create `job-details` based on `job-feed`.

That way you would just need to sync each branch with it's parent once it's merged to master then delete the parent when you're done, with that I don't think you will ever get merge conflicts and each PR will only have the changes you made for that feature so you don't have to copy/paste stuff, does that make sense?

2021-03-17 12:17 UTC, ahmed-gz commented
@Aaron-Goldman Ideally we want to achieve a clean diff between child and parent branches like this:

- https://github.com/Aaron-Goldman/internship-job-portal/compare/auth...Aaron-Goldman:navbar
- https://github.com/Aaron-Goldman/internship-job-portal/compare/navbar...Aaron-Goldman:job-feed
- https://github.com/Aaron-Goldman/internship-job-portal/compare/job-feed...Aaron-Goldman:job-details

Also please delete the branches that are no longer needed in your repo!

2021-03-18 02:36 UTC, Aaron-Goldman commented
The PR branches should be fixed now.

2021-03-18 11:20 UTC, ahmed-gz requested changes
Looks good, left some suggestions!

2021-03-18 11:20 UTC, ahmed-gz commented on src/NavBar.js
> +  };
You can make this shorter like this if you want: `const handleSignOut = () => auth.signOut();`

2021-03-18 11:20 UTC, ahmed-gz commented on src/NavBar.js
> +import React from 'react';
Similar to other features, please move this file to `src/NavBar/index.js`

2021-03-18 11:20 UTC, ahmed-gz commented on src/NavBar.test.js
> +import React from 'react';
Similar to other features, please move this file to `src/NavBar/index.test.js`

2021-03-22 09:05 UTC, ahmed-gz requested changes
Looks good, left one last suggestion!

2021-03-22 09:05 UTC, ahmed-gz commented on src/App.js
> +import NavBar from './Navbar';
For consistency let's use the same name for the file and its default export, preferably:
`import Navbar from './Navbar';`

2021-03-22 09:05 UTC, ahmed-gz commented on src/Navbar/index.js
> +function NavBar() {
For consistency let's use the same name as the file `Navbar`

2021-03-23 09:43 UTC, ahmed-gz approved these changes
Looks great, feel free to merge it 👍

2021-03-23 19:10 UTC, merged