Job details page
Aaron-Goldman/internship-job-portal pull request #9
Opened 2021-03-15 14:10 UTC by Aaron-Goldman

Added job details page that displays a list of skills, benefits, and requirements of a job. Job is specified with job id in URL.

Should be merged after #7.

close #8

2021-03-18 12:01 UTC, ahmed-gz requested changes
Looks good, left some suggestions!

2021-03-18 12:01 UTC, ahmed-gz commented on src/JobDetails/index.js
> +  const j = data.job;
I suggest you use destructing here to get the properties you need directly

2021-03-18 12:01 UTC, ahmed-gz commented on src/JobDetails/index.js
> +          {j.jobSkills.map((s) => (
You can use destructing here: `{jobSkills.map(({ skill: { id, name } }) => (`

2021-03-18 12:01 UTC, ahmed-gz commented on src/JobDetails/index.js
> +          {j.jobRequirements.map((r) => (
Destructing same as above

2021-03-18 12:01 UTC, ahmed-gz commented on src/JobDetails/index.js
> +          {j.jobBenefits.map((b) => (
Destructing same as above

2021-03-18 12:01 UTC, ahmed-gz commented on src/JobDetails/index.js
> +    variables: { id: parseInt(id, 10) },
Would this work: `Number(id)` ?

2021-03-18 12:01 UTC, ahmed-gz commented on src/JobDetails/index.js
> +  const { loading, error, data } = useQuery(QUERY_JOB_DETAILS, {
`const { loading, error, data: { job } }`

2021-03-18 12:01 UTC, ahmed-gz commented on src/JobDetails/index.test.js
> +      <Router initialEntries={[`/job-details/${MOCK_JOB_ID}`]}>
For consistency let's use `JOB_DETAILS_BASE_PATH` here

2021-03-20 17:28 UTC, Aaron-Goldman commented on src/JobDetails/index.js
> +  const { loading, error, data } = useQuery(QUERY_JOB_DETAILS, {
This one causes a runtime error because `data` is undefined until the query is completed.

2021-03-20 18:16 UTC, Aaron-Goldman commented on src/JobDetails/index.js
> +  const { loading, error, data } = useQuery(QUERY_JOB_DETAILS, {
Using a state variable for `job` and setting up a callback that changes it after the query finishes works.

2021-03-22 08:58 UTC, ahmed-gz commented on src/JobDetails/index.js
> +  const { loading, error, data } = useQuery(QUERY_JOB_DETAILS, {
@Aaron-Goldman I didn't know data can be undefined, so you can ignore my comment, if it works as it it right now I would avoid creating a state variable just for job data, my suggestion was only a code quality improvement and to use destructing as much as possible to use duplication of accessing properties of an object.

2021-03-23 09:48 UTC, ahmed-gz approved these changes
Looks great, feel free to merge it 👍

2021-03-23 19:12 UTC, merged